server:
  port: 8080

spring:
  application:
    name: client
  thymeleaf:
    cache: false

client:
  daas:
    base-url: http://localhost:8081
  eaas:
    base-url: http://localhost:8082

logging:
  level:
    it.univaq.sose: INFO
