server:
  port: 8081

spring:
  application:
    name: daas-service

daas:
  dataset:
    file: data/employment.rdf
    seed: classpath:dataset/employment.rdf

logging:
  level:
    it.univaq.sose: INFO
    org.apache.jena: WARN
